### ISSUE TITLE
jdk的版本问题

### ISSUE THREAD

**Issue by bikot1205** [PingPlusPlus/pingpp-java#10]
请问一下你们的java的jdk的版本支持多少？

我本机的jdk是1.6.02，运行你们的demo就出下面的版本不对的错误信息。
java.lang.UnsupportedClassVersionError: example/WxPubOAuthExample : Unsupported major.minor version 51.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:620) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124) at java.net.URLClassLoader.defineClass(URLClassLoader.java:260) at java.net.URLClassLoader.access$000(URLClassLoader.java:56) at java.net.URLClassLoader$1.run(URLClassLoader.java:195) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:188) at java.lang.ClassLoader.loadClass(ClassLoader.java:306) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:276) at java.lang.ClassLoader.loadClass(ClassLoader.java:251) at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319) Exception in thread "main"

**Comment by samurai00** [comment]
你好，你用的是哪个版本的 SDK。我这边 2.1.3 的 SDK 可以在 1.6.0_65 下正常运行。
另外再提供一下调用的前后文吧
