### ISSUE TITLE
创建charge对象subject传入中文

### ISSUE THREAD

**Issue by domnli** [PingPlusPlus/pingpp-java#11]
银联接口 创建charge对象subject传入中文时报签名错误

**Comment by samurai00** [comment]
传中文本身是不会有问题的。你试过传纯英文可以吗？具体报错信息可以贴一下

**Comment by domnli** [comment]
创建charge对象接口 subject传中文传英文都能正常返回charge对象,传英文时银联的交易流程能走通，但传中文时银联返回**交易失败:签名错误**

**Comment by samurai00** [comment]
你是说传中文跳转到支付页面时，显示这个错误吗？是 PC 的还是手机的？

**Comment by domnli** [comment]
对的  银联支付界面上显示这个错误  前端用的 HTML5 sdk
