### ISSUE TITLE
如果 apiKey 需要在程序中有多个应该怎么做？

### ISSUE THREAD

**Issue by chenzhenjia** [PingPlusPlus/pingpp-java#13]
万一我要在程序中使用会有多个apiKey 配置，那需要怎么做？我看到 sdk 里面是写成 static 的，所以想问下。

**Comment by samurai00** [comment]
调用接口之前设置就好了。

**Comment by chenzhenjia** [comment]
但是我初始化的时候用的是单例，我在初始化 appKey 是在单例的构造中初始化的，希望能把 appKey 改为不是静态的。

**Comment by samurai00** [comment]
Charge create 方法也是静态的，所以都是一个道理。如果你想自定义的话，你也可以自己根据源代码修改的。
