### ISSUE TITLE
不支持jdk1.7的版本

### ISSUE THREAD

**Issue by JohnConnor010** [PingPlusPlus/pingpp-java#25]
jar包2.3.1不支持jdk1.7的版本

**Comment by JohnConnor010** [comment]
我们的项目的运行环境使用的是JDK1.7，但是在加载了ping++ 2.3.1版本的SDK后，启动报错。错误信息如下：
java.lang.UnsupportedClassVersionError: com/pingplusplus/exception/RateLimitException : Unsupported major.minor version 52.0 (unable to load class com.pingplusplus.exception.RateLimitException)
从错误信息来看，应该是这个类是在JDK1.8版本上编译的，所以在JDK1.7版本上运行不起来。

**Comment by samurai00** [comment]
使用 2.3.2 试试
