### ISSUE TITLE
PingppObject类中GsonBuilder注册registerTypeAdapter的疑问。

### ISSUE THREAD

**Issue by zhumenglong** [PingPlusPlus/pingpp-java#28]
public static final Gson PRETTY_PRINT_GSON = new GsonBuilder()
            .setPrettyPrinting()
            .serializeNulls()
            .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
            .disableHtmlEscaping()
            .registerTypeAdapter(BatchTransferRecipientSerializer.class, new BatchTransferRecipientSerializer())
            .registerTypeAdapter(BatchRefundCharges.class, new BatchRefundChargesSerializer())
            .registerTypeAdapter(Double.class, new DoubleTypeSerializer())
            .registerTypeAdapter(ChargeEssentials.class, new ChargeEssentialsSerializer())
            .registerTypeAdapter(CouponTemplateExpiration.class, new CouponTemplateExpirationSerializer())
            .registerTypeAdapter(SettleAccountRecipient.class, new SettleAccountRecipientSerializer())
            .create();

这里的registerTypeAdapter(BatchTransferRecipientSerializer.class, new BatchTransferRecipientSerializer()是不是应该为：            .registerTypeAdapter(BatchTransferRecipient.class, new BatchTransferRecipientSerializer())

**Comment by samurai00** [comment]
确实是。不过还好，问题不大，就是序列化时没把多余的 null 值去掉。
下个版本改掉。
