### ISSUE TITLE
使用sdk创建charge出错

### ISSUE THREAD

**Issue by zhric** [PingPlusPlus/pingpp-java#30]
com.pingplusplus.exception.InvalidRequestException: 没有提供签名串，需要在 header 中加入签名串。; type: invalid_request_error

```
com.pingplusplus.exception.InvalidRequestException: 没有提供签名串，需要在 header 中加入签名串。; type: invalid_request_error
	at com.pingplusplus.net.APIResource.handleAPIError(APIResource.java:248)
	at com.pingplusplus.net.APIResource.request(APIResource.java:209)
	at com.pingplusplus.model.Charge.create(Charge.java:284)
```

**Comment by samurai00** [comment]
应该是没有设置私钥，或者私钥格式不正确。
1. 参考[这里](https://github.com/PingPlusPlus/pingpp-java/blob/master/docs/update/2.3-to-2.4.md#1-requestoptions)使用`RequestOptions` 设置 PrivateKey;
2. 如果私钥格式不是 `PKCS#8`，请[转换](https://github.com/PingPlusPlus/pingpp-java/blob/master/docs/update/2.3-to-2.4.md#5-private-key)成 `PKCS#8` 的。

**Comment by zmzmdr** [comment]
检查一下这个库的版本，如果太高也会出这个问题！


    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt</artifactId>
      <version>0.7.0</version>
    </dependency>
