### ISSUE TITLE
pingpp-java.2.1.0 not found

### ISSUE THREAD

**Issue by ThomasKwokYesasia** [PingPlusPlus/pingpp-java#8]
I fail to down the version 2.1.0.

http://jcenter.bintray.com/Pingplusplus/pingpp-java/2.1.0/pingpp-java-2.1.0.jar

But I can down the version 2.0.10.

Please advice which version to use.

**Comment by samurai00** [comment]
@ThomasKwokYesasia 你再试试。之前好像没上传成功。
